platform :ios, '11.0'

abstract_target 'defaults' do
  use_frameworks!

  pod 'SwiftLint', '~> 0.30.1'
  pod 'SwiftFormat/CLI', '~> 0.38.0'

  # App

  target 'iOSNights2019'

  # Tests

  target 'iOSNights2019Tests'
  target 'iOSNights2019UITests'
end
